/* automatically generated by rust-bindgen 0.71.1 */

pub mod pageflags {
    pub type Type = ::aya_ebpf::cty::c_uint;
    pub const PG_locked: Type = 0;
    pub const PG_writeback: Type = 1;
    pub const PG_referenced: Type = 2;
    pub const PG_uptodate: Type = 3;
    pub const PG_dirty: Type = 4;
    pub const PG_lru: Type = 5;
    pub const PG_head: Type = 6;
    pub const PG_waiters: Type = 7;
    pub const PG_active: Type = 8;
    pub const PG_workingset: Type = 9;
    pub const PG_owner_priv_1: Type = 10;
    pub const PG_owner_2: Type = 11;
    pub const PG_arch_1: Type = 12;
    pub const PG_reserved: Type = 13;
    pub const PG_private: Type = 14;
    pub const PG_private_2: Type = 15;
    pub const PG_reclaim: Type = 16;
    pub const PG_swapbacked: Type = 17;
    pub const PG_unevictable: Type = 18;
    pub const PG_dropbehind: Type = 19;
    pub const PG_mlocked: Type = 20;
    pub const PG_hwpoison: Type = 21;
    pub const PG_young: Type = 22;
    pub const PG_idle: Type = 23;
    pub const PG_arch_2: Type = 24;
    pub const __NR_PAGEFLAGS: Type = 25;
    pub const PG_readahead: Type = 16;
    pub const PG_swapcache: Type = 10;
    pub const PG_checked: Type = 10;
    pub const PG_anon_exclusive: Type = 11;
    pub const PG_mappedtodisk: Type = 11;
    pub const PG_fscache: Type = 15;
    pub const PG_pinned: Type = 10;
    pub const PG_savepinned: Type = 4;
    pub const PG_foreign: Type = 10;
    pub const PG_xen_remapped: Type = 10;
    pub const PG_isolated: Type = 16;
    pub const PG_reported: Type = 3;
    pub const PG_vmemmap_self_hosted: Type = 10;
    pub const PG_has_hwpoisoned: Type = 8;
    pub const PG_large_rmappable: Type = 9;
    pub const PG_partially_mapped: Type = 16;
}

